---
title: "Dataframe Manipulation with dplyr"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
gapminder = read.csv("/data/gapminder_data.csv")
```

```{r}
mean(gapminder[gapminder$continent == "Africa","gdpPercap"])
```

```{r}
mean(gapminder[gapminder$continent == "Americas","gdpPercap"])
```

```{r}
mean(gapminder[gapminder$continent == "Asia","gdpPercap"])
```

select
filter
group_by
summarize # summarise
mutate

```{r}
library(dplyr)
```

```{r}
year_country_gdp = select(gapminder, "year", "country", "gdpPercap")
year_country_gdp
```

```{r}
year_country_gdp <- gapminder %>% select(year, country, gdpPercap)
year_country_gdp
```

```{r}
gapminder %>%
  select(year,country, gdpPercap) ->
  year_country_gdp
```


# Filter

```{r}
gapminder %>%
  filter(continent=="Europe") %>%
  select(year, country, gdpPercap)
```

# group_by and summarize

Europe 288373892
Asia   3928987398723409
Oceania 098309
Africa  0983049820390





```{r}
gapminder %>%
  group_by(continent) %>%
  str
```


```{r}
str(gapminder)
```


```{r}
gapminder %>%
  group_by(continent) %>%
  summarise(mean_gdpPercap = mean(gdpPercap))
```

```{r}
gapminder %>%
  group_by(continent, year) %>%
  summarise(mean_gdpPercap = mean(gdpPercap), 
            sd_gdpPercap = sd(gdpPercap), 
            mean_pop = mean(pop), 
            sd_pop = sd(pop))
```

# count() and n()

```{r}
gapminder %>%
  filter(year==2002) %>%
  count(continent, sort=TRUE)
```

```{r}
gapminder %>%
  group_by(continent) %>%
  summarise(se_le =sd(lifeExp)/sqrt(n()),
            mean_le = mean(lifeExp),
            max_le = max(lifeExp))
```



# mutant
```{r}
gapminder
```



```{r}
gapminder %>%
  mutate(gdp = gdpPercap*pop,
         gdp_billion = gdpPercap*pop/10^9) %>%
  group_by(continent,year) %>%
  summarise(mean_gdpPercap = mean(gdpPercap),
            mean_pop=mean(pop),
            mean_gdp_billion = mean(gdp_billion))
```


## counting with n
```{r}
gapminder %>%
  filter(year==2002) %>%
  group_by(continent) %>%
  summarise(num_countries = n()) %>%
  arrange(desc(num_countries))
```

# Combining dplyr & ggplot2

```{r}
library(ggplot2)
library(stringr)
```

```{r}
# Get the start letter of each country
starts.with <- substr(gapminder$country, start = 1, stop = 1)
# Filter countries that start with "A" or "Z"
az.countries <- gapminder[starts.with %in% c("A", "Z"), ]
# Make the plot
ggplot(data = az.countries, aes(x = year, y = lifeExp, color = continent)) +
  geom_line() + facet_wrap( ~ country)
```

```{r}
gapminder %>%
  pull(country) %>%
  str_starts("A")
```


```{r}
gapminder %>%
  filter(str_starts(country,"A|Z")) %>%
  ggplot(aes(x = year, y = lifeExp, color = continent)) +
  geom_line() + facet_wrap( ~ country)
```






```{r}
gapminder = read.csv("/data/gapminder_data.csv")
```

# Right assignment
```{r}
gdp_future_bycontinents_byyear_high_lifeExp <- gapminder %>%
    mutate(gdp_futureExpectation = ifelse(lifeExp > 40, gdpPercap * 1.5, gdpPercap)) %>%
    group_by(continent, year) %>%
    summarize(mean_gdpPercap = mean(gdpPercap),
              mean_gdpPercap_expected = mean(gdp_futureExpectation))
```

```{r}
gapminder %>%
  mutate(gdp_futureExpectation = ifelse(lifeExp > 40, gdpPercap * 1.5, gdpPercap)) %>%
  group_by(continent, year) %>%
  summarize(mean_gdpPercap = mean(gdpPercap),
            mean_gdpPercap_expected = mean(gdp_futureExpectation)) ->
  gdp_future_bycontinents_byyear_high_lifeExp

```

# Yet another way (stringr)
```{r}
library(stringr)
library(ggplot2)
gapminder %>%
	dplyr::filter(str_starts(country, "^A|^Z")) %>%
	# Make the plot
	ggplot(aes(x = year, y = lifeExp, color = continent)) +
	geom_line() +
	facet_wrap( ~ country)
```

