---
title: "Data Frames"
output: html_document
---


```{r}
cats = read.csv("data/feline-data.csv")
cats
```

```{r}
age = c(2,3,5)
cbind(cats,age)
```

```{r}
cats
```

```{r}
age = c(2, 3)
cbind(cats, age)
```

```{r}
nrow(cats)
```

```{r}
length(age)
```

```{r}
age = c(2,3,5)
old_cats = cats
cats = cbind(cats,age)
```

```{r}
cats
```

```{r}
old_cats
```

```{r}
newRow = list("tortioseshell", 3.3, TRUE, 9)
rbind(cats, newRow)
```

```{r}
as.integer(c(1, "apple", 3))
```


```{r}
cats$coat
```

```{r}
factor(c("apple", "pear", "plum", "appple"))
```
```{r}
# levels(cats$coat) = 
# c(levels(cats$coat), "tortoiseshell")
# levels(cats$coat)
levels(cats$coat) = c(levels(cats$coat), "tortoiseshell")
levels(cats$coat)
```
```{r}
cats
```

```{r}
newRow = list("tortoiseshell", 3.3, TRUE, 9)
cats = rbind(cats, newRow)
```

```{r}
cats[c(1,3), ]
```
```{r}
y = cats[c(3,3,1,2), ]
y
```

```{r}
y[1,]
```


```{r}
cats
```

```{r}
cats["weight", "coat"]
```


```{r}
cats[,c("age", "weight")]
```

```{r}
newcats = cats[-3,]
rownames(newcats) = c("apple", "pear", "banana")
newcats
```

```{r}
newcats2 = cats[-3,]
newcats2
rownames(newcats2) = NULL
rownames(newcats2)
newcats2
```

## Appending to Data Frames

```{r}
cats
twocats = (rbind(cats, cats))
rownames(twocats)
```

## Realistics
```{r}
gapminder = read.csv("/data/gapminder_data.csv")
```

```{r}
download.file("https://raw.githubusercontent.com/swcarpentry/r-novice-gapminder/gh-pages/_episodes_rmd/data/gapminder_data.csv", destfile = "data/gapminder_data.csv")
```
```{r}
str(gapminder)
```
```{r}
```


```{r}
range(gapminder$lifeExp)
```
```{r}
length(gapminder)
```
```{r}
nrow(gapminder)
```

```{r}
dim(gapminder)
```


```{r}
ncol(gapminder)
```

```{r}
head(gapminder, n=10)
```



http://swcarpentry.github.io/r-novice-gapminder/05-data-structures-part2/index.html#realistic-example
